# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Use VirtualBox
USE_PROVIDER = "virtualbox"
NETWORK_PRIVATE_IP_PREFIX = "172.16.3."

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.ssh.port = 49222
  #config.vm.network "forwarded_port", guest: 49222, host: 2222, protocol: "tcp", id: 'ssh'
  #config.vm.network "forwarded_port", guest: 22, host: 2224, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 49222, host: 49222, protocol: "tcp", id: 'ssh'

  #VirtualBox
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define "ubuntu1604" do |ubuntu1604|
    ubuntu1604.vm.hostname = "ubuntu1604test"
    #ubuntu1604.vm.box = "geerlingguy/ubuntu1604"
    ubuntu1604.vm.box = "ubuntu/xenial64"
    ubuntu1604.vm.network :private_network, ip: NETWORK_PRIVATE_IP_PREFIX + "2"

    # Provision
    ubuntu1604.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      #ansible.verbose = "-vvv"
      #ansible.become = true
      #ansible.ask_become_pass = true
      ansible.extra_vars = {
        hardening_ssh: "False",
        cowrie_clear_database: "True",
        #hardening_iptables: "False"
        ansible_port: 49222
      }
    end
  end
end
